from typing import List

from villageswar.villager import Villager


class Village(object):
    ...

    def __init__(self, name):
        self.population = None # type: List[Villager]
        self.name = None # type: str
        self.data = None # type: dict
        ...

    def day_start(self): ...

    def population_activities(self): ...

    def day_end(self): ...

    def remove_dead(self): ...

    def birth(self, baby_stats: (bool, dict)): ...

    def __repr__(self) -> str: ...
